//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    public partial class Financial
    {
        public int ID { get; set; }

        public int Year { get; set; }

        public long Asset { get; set; }

        public long Liabilities { get; set; }

        public long Equities { get; set; }

        public int Status { get; set; }
    }
}
